### ISSUE TITLE
Triggers support

### ISSUE THREAD

**Issue by douglascorrea** [steida/firebase#10]
This is a long term promise from Firebase team. Just put it here to keep track of it.

The last "almost there" news came with 3.0 keynote where they said that will work together with Google Cloud Function team to have something like "Triggers"

**Comment by jwngr** [comment]
Note that you can start playing around with [Google Cloud Functions](https://cloud.google.com/functions/) today, although it is still in alpha (aka not ready for production use). We are in fact working with that team to bring some Firebase magic to it.

**Comment by douglascorrea** [comment]
@jwngr Thanks commenting here.

Today the only way to use Google Cloud Functions from Firebase API is creating a "fake-bucket" where I will ping something that will trigger a Cloud Function call. That works the same way of https://github.com/firebase/firebase-queue in an private node (we need to put something in the queue to be processed).

But I think the "Triggers" idea is a little more than that. I imagine a "Trigger solution" where I can set a specific "Cloud Function" to be called as soon one specific path of my Firebase database got updated.

**Comment by douglascorrea** [comment]
@jwngr also thanks for

**Comment by jwngr** [comment]
Yup, you want the Firebase Database to be a GCF "trigger." We are very keen to make this happen but don't have any timelines for you at the moment.

**Comment by douglascorrea** [comment]
@jwngr but thanks anyway for the suggestion about applying for Cloud Functions alpha, their welcome email gave me hope about Firebase integration ;)

**Comment by mcdonamp** [comment]
I strongly recommend **not** using the "fake bucket" solution, unless you're legitimately using Firebase Storage -> GCF (as shown [here](https://github.com/mcdonamp/flaming-specs), which then writes back to the DB). As Jacob said, we're totally on board with that idea though :)

**Comment by RdeWilde** [comment]
Any update on this?

**Comment by Danm72** [comment]
Anything new here?

**Comment by steida** [comment]
@Danm72 I am going to try https://www.graph.cool

**Comment by mcdonamp** [comment]
I recommend tuning in to the Next '17 keynote for some updates: https://cloudnext.withgoogle.com/ ;)
