### ISSUE TITLE
Re-introduce Realtime Database usage / analytics panel into new console

### ISSUE THREAD

**Issue by douglascorrea** [steida/firebase#11]
To check how much from Quota we already used.

More details here: https://groups.google.com/d/msgid/firebase-talk/32fb7438-8ca4-433a-8342-651cda9767d6%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by jwngr** [comment]
Slightly changed the title to better reflect what this is actually called. This is a very high priority issue for us which is unfortunately blocked on a couple internal things. We realize this is an issue for people and will get it back (and better than ever) as soon as we can.
