### ISSUE TITLE
Why once method second (cancel) callback isn't documented?

### ISSUE THREAD

**Issue by steida** [steida/firebase#13]
It's convenient to have the same API as `on` has.

**Comment by jwngr** [comment]
This is just a documentation bug. I'm putting together a fix now.

**Comment by jwngr** [comment]
Finally got this published: https://firebase.google.com/docs/reference/js/firebase.database.Reference#once

**Comment by steida** [comment]
Isn't it beautiful to have public issue tracker? ;-)
