### ISSUE TITLE
signInWithRedirect doesn't work in embedded Safari in iOS Facebook App

### ISSUE THREAD

**Issue by steida** [steida/firebase#15]
This flow works in iOS Safari and Chrome, but in Facebook embedded Safari it fails with code: 'auth/network-request-failed'. 

```js
async function socialSignIn(firebaseAuth, providerName) {
  const provider = new firebaseAuth.FacebookAuthProvider();
  provider.addScope('email,user_friends'); // or user_birthday etc.
  try {
    return await firebaseAuth().signInWithPopup(provider);
  } catch (error) {
    if (error.code === 'auth/popup-blocked') {
      try {
        await firebaseAuth().signInWithRedirect(provider);
      } catch (error) {
        // alert (error.code) shows 'auth/network-request-failed'.
        alert(JSON.stringify(error))
      }
    } else {
      throw error;
    }
  }
}
```

I don't know why Safari and Chrome works, while Facebook embedded browser does not. Configuration?

**Comment by steida** [comment]
Damn, http://10.0.1.3:8000/auth/facebook-redirect.html on device works. Hmm.

**Comment by steida** [comment]
Damn, this works. There is something broken with signInWithPopup probably.

```js
async function socialSignIn(firebaseAuth, providerName) {
  const provider = new firebaseAuth.FacebookAuthProvider();
  provider.addScope('email,user_friends'); // or user_birthday etc.
  firebaseAuth().signInWithRedirect(provider);
}
```

**Comment by steida** [comment]
@jwngr Ok, so signInWithPopup called in iOS Facebook embedded browsers somehow screw up the whole app. Try to call `signInWithPopup`, strange things happen. It seems app was reloaded then died. 

That's because firebase/quickstart-js doesn't contain signInWithPopup then signInWithRedirect example.

**Comment by steida** [comment]
To demonstrate it, open quickstart-js signInWithPopup in Facebook. Hint: Write status with link, then click to it.

**Comment by jwngr** [comment]
Looks like discussion is ongoing with Bassam on the Google Group thread [here](https://groups.google.com/forum/#!msg/firebase-talk/643d_lwUAMI/bfQyn8D-BQAJ). Bassam is the person you want to be talking to, so let's keep the discussion there.

**Comment by steida** [comment]
@jwngr How I workarounded it https://github.com/este/este/commit/3cf8280650e516b3732ecca0d027fd34958cdb92

Maybe it should be mentioned in docs because Firebase in App browser is very very popular and the fix is tricky.

**Comment by steida** [comment]
@jwngr Still doesn't work with JavaScript SDK (v3.3.0)
