### ISSUE TITLE
signInWithCredential doesn't work with react-native 0.31 when the remote debug mode is on

### ISSUE THREAD

**Issue by element6** [steida/firebase#19]
You can replicate the issue by checking out este.js commit <1bbcca2eb1797d5fd9d88f303336b96ce357b0b5>, which is the latest at the moment. 

I am using genymotion(2.7.2) with Google Nexus 4 - 4.1.1 - API 16 768x1280 image. 
Steps to reproduce the error:

```
npm install
gulp android
```

Turn on remote debug, then try to login with facebook. Nothing happens.
But if you change react-native to 0.30, instead of 0.31, it works.

Original issue thread: https://github.com/este/este/issues/1059

**Comment by steida** [comment]
Ping @jwngr

**Comment by steida** [comment]
Anyway, it looks like a regression in React Native. @element6 please check similar issues. Thank you.
