### ISSUE TITLE
Firebase 3 adds 66kb gzipped

### ISSUE THREAD

**Issue by steida** [steida/firebase#3]
115 kb now

**Comment by jwngr** [comment]
Answered on the Firebase Google Group [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/firebase-talk/ZYp3SJKo8uA/L9t6PVFsFwAJ).

**Comment by jwngr** [comment]
Just to follow up here, we are working on reducing the package size. The `3.1.0` release brings us down to 96 kb. Note that the web SDK now includes a new product (Firebase Storage) and the entire auth stack was rewritten (with a fair amount of extra functionality). We realize this is an important consideration though and will continue to find places where we can minimize package size.

Note that we now have [documentation on how to minimize package size](https://firebase.google.com/docs/web/setup#add_firebase_to_your_app) for use with bundlers like Browserify or webpack.

**Comment by steida** [comment]
Hats off :-)
