### ISSUE TITLE
Not working auth workflow for signInWithRedirect after signInWithPopup

### ISSUE THREAD

**Issue by steida** [steida/firebase#4]
Should we detect mobile platform now? It's almost impossible. What was the algorithm behind Firebase 2 signInWithPopup rejection?

**Comment by steida** [comment]
It seems iOS Chrome finally handle signInWithPopup, while embedded Safari, for example in Facebook app, still fails with 
![img_2426](https://cloud.githubusercontent.com/assets/66249/15490862/c609f3cc-216b-11e6-8b84-ab2ca4731f3b.PNG)

**Comment by steida** [comment]
https://github.com/firebase/quickstart-jshttps://github.com/firebase/quickstart-js

**Comment by steida** [comment]
Ok, another horrible issue. Redirect doesn't work at all when used after auth popup

https://groups.google.com/forum/#!topic/firebase-talk/643d_lwUAMI

**Comment by jwngr** [comment]
Unfortunately, I don't think this report is very actionable. Bassam responded on the Google Groups post and wasn't able to reproduce your issue. Can you confirm that this is still an issue and put together a minimal repro?

**Comment by steida** [comment]
Sure. Thank you for your precious effort. I will try to update Este to Firebase 3 and will report the result.

**Comment by steida** [comment]
Related #15
