### ISSUE TITLE
Browser document is used so it doesn't work in React Native

### ISSUE THREAD

**Issue by steida** [steida/firebase#5]
That's because Google is eating only own dog food :-/

**Comment by jwngr** [comment]
I don't have a ton of context on why the things in the `3.x.x` libraries use `document` and other things not supported in React Native, but I feel fairly confident in saying that dropping React Native was not an intentional decision. I've seen a ton of support cases on this subject and it's one of the many complaints being raised internally (in addition to us dropping OSX support with the `3.x.x` iOS SDK).

**Comment by steida** [comment]
ETA please?

**Comment by jwngr** [comment]
As I'm sure you know from being active on our Google Group, we don't offer public ETAs on features. That being said, I think you will be seeing this very soon.

**Comment by jwngr** [comment]
React Native support is now compatible with the JavaScript SDK with today's `3.1.0` release. Release notes are [here](https://firebase.google.com/support/release-notes/js#3.1.0). There are two known limitations:
 1. React Native does not support the `File` and `Blob` types, so Firebase Storage uploads do not work in React Native. File downloads do work though.
 2. "Headful" auth methods such as `signInWithPopup()`, `signInWithRedirect()`, `linkWithPopup()`, and `linkWithRedirect()` do not work in React Native (or Cordova, for that matter). You can still sign in or link with a federated provider by using `signInWithCredential()` with an OAuth token from your provider of choice.

**Comment by steida** [comment]
Thank you again.

**Comment by steida** [comment]
@jwngr As for Firebase Storage upload, which browsers are supported? The same question for whole Firebase. I was not able to find supported browser table.

**Comment by jwngr** [comment]
File uploads for all browsers which support `File` and / or `Blob` should "just work." As for the rest of the SDK, it should work on all major browsers for at least the last two major versions. I'm not sure of the exact compatibility to be honest.
