### ISSUE TITLE
Permission denied to access property "closed"

### ISSUE THREAD

**Issue by steida** [steida/firebase#7]
So my Sentry reports me

```
Permission denied to access property "closed"
~/firebase/lib/firebase-web.js in func at line 138:496

{snip} "":"?")+Ib(b);var l=window.open(a,this.options.window_name,this.options.window_features);k||(k=l);var t=setInterval(function(){l&&l.closed&&
~/raven-js/src/raven.js in func at line 265:0

return func.apply(this, args);
```

```
browser = Firefox 46.0device = Otherlevel = errorlogger = javascriptos = Linuxrelease = d739e9f2eda5929e73b7832d3476a018ceec2d0burl = https://este.firebaseapp.com/firebaseuser = ip:89.31.160.153
```

Should not report it I suppose.

**Comment by jwngr** [comment]
I'm not really sure what this means to be honest. Does Sentry report any more information?

**Comment by steida** [comment]
I have no such property in my code, so it's probably something from Firebase. That's all I have.

Again. If you would open source client, I could check your code and help you ;-)

![screen shot 2016-06-01 at 00 19 52](https://cloud.githubusercontent.com/assets/66249/15692434/a0c9b7ea-278e-11e6-8c14-e6bcc758b36f.png)
